# Generated by Django 2.2.4 on 2019-09-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='round_type',
            field=models.CharField(default='W', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(default='I', max_length=10),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ts_contributed', models.DateField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='esusu.Group')),
                ('memeber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='esusu.Membership')),
            ],
        ),
    ]
