# Generated by Django 2.2.4 on 2019-09-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0002_auto_20190907_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='memeber',
            new_name='member',
        ),
    ]
