# Generated by Django 2.2.4 on 2019-09-10 21:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0005_auto_20190908_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='ts_contributed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ts_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='ts_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ts_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_from', models.DateField(auto_now_add=True)),
                ('ts_end_date', models.DateField()),
                ('collection_sequence', django.contrib.postgres.fields.jsonb.JSONField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='esusu.Group')),
            ],
        ),
    ]
