# Generated by Django 2.2.4 on 2019-09-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0006_auto_20190910_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenure',
            name='collection_sequence',
        ),
        migrations.AlterField(
            model_name='tenure',
            name='ts_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
