# Generated by Django 2.2.4 on 2019-09-10 22:32

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0007_auto_20190910_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenure',
            name='collection_sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=datetime.datetime(2019, 9, 10, 22, 32, 3, 150045).isoformat()),
            preserve_default=False,
        ),
    ]
