# Generated by Django 2.2.4 on 2019-09-10 23:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0008_tenure_collection_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenure',
            name='collection_sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
