# Generated by Django 2.2.4 on 2019-09-13 17:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esusu', '0009_auto_20190910_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenure',
            name='status',
            field=models.CharField(default='A', editable=False, help_text="When a tenure's value of `ts_end_date` the status will become inactive and cannot be changed", max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contrib_amount',
            field=models.IntegerField(default=0, help_text='The amount to be contributed , this is fixed by the group admin when creating the group'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group to contribute to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='esusu.Group'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(help_text='The member making the contribution, must be an already active member', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='esusu.Membership'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='ts_contributed',
            field=models.DateField(auto_now_add=True, help_text='When was the contribution made'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(help_text='The User who created the group', on_delete=django.db.models.deletion.PROTECT, related_name='groups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=True, help_text='How many members will the group have'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contrib_amount',
            field=models.IntegerField(default=0, help_text='The amount to be contributed every round '),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(help_text='Tell people more about the group', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique uuid for a group', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_searchable',
            field=models.BooleanField(default=False, help_text='Set to true if you want the group to be private and invincible to other users, default to False'),
        ),
        migrations.AlterField(
            model_name='group',
            name='round_type',
            field=models.CharField(default='W', help_text='The types of rounds, could be W(weekly), M(monthly), D(Daily) ', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group you want to join, must be a valid and active existing group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='esusu.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(default='I', help_text='Used to place an embargo on a member, can be A(active) or I(inactive)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='collection_sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This is a sequence of collection sorted randomly for every member when the tenure starts', null=True),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='group',
            field=models.OneToOneField(help_text='The group to create a tenure for, must be a valid group that isnt in an active tenure', on_delete=django.db.models.deletion.PROTECT, to='esusu.Group'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='ts_end_date',
            field=models.DateField(blank=True, help_text='When the tenure ends or shall end', null=True),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='ts_from',
            field=models.DateField(auto_now_add=True, help_text='when the tenure starts'),
        ),
    ]
